import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import "remixicon/fonts/remixicon.css";
import Footer from "@/components/layout/footer";
import { Toaster } from "@/components/ui/toaster";
import Provider from "./provider";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "600", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        > */}
        <Provider>
          {children}
          <Toaster />
          <Footer />
        </Provider>
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
