import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import NavbarSearch from "@/components/NavbarSearch";
import "remixicon/fonts/remixicon.css";

const inter = Poppins({ subsets: ["latin"], weight: "200" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarSearch type="home" />
        {children}
      </body>
    </html>
  );
}
